### ISSUE TITLE
some CI bots failing with missing enum in clspv::reflection

### ISSUE THREAD

**Issue by dneto0** [google/clspv#898]
/tmpfs/src/github/clspv/lib/SPIRVProducerPass.cpp:6868:27: error: no member named 'ExtInstImageArgumentInfoChannelOrderPushConstant' in namespace 'clspv::reflection'
              reflection::ExtInstImageArgumentInfoChannelOrderPushConstant;
              ~~~~~~~~~~~~^
/tmpfs/src/github/clspv/lib/SPIRVProducerPass.cpp:6872:27: error: no member named 'ExtInstImageArgumentInfoChannelDataTypePushConstant' in namespace 'clspv::reflection'
              reflection::ExtInstImageArgumentInfoChannelDataTypePushConstant;
              ~~~~~~~~~~~~^

Seems to be introduced by #882, but only affects certain bots.

CI-amber-ubuntu-gcc-release
CI-clvk-ubuntu-clang-debug

Are the bots for those projects not getting the right Clspv sources?

**Comment by rjodinchr** [comment]
I think those bots do not have the updated version of the spirv-headers (including commit https://github.com/KhronosGroup/SPIRV-Headers/commit/0bcc624926a25a2a273d07877fd25a6ff5ba1cfb) that is now needed for clspv.

**Comment by dneto0** [comment]
Ah, so if I roll the amber SPIRV-Headers in amber should work.
I see. I had not traced the dependency through the generated headers yet.

I'll look at updating Amber.

**Comment by dneto0** [comment]
Thanks @rjodinchr you already posted https://github.com/kpet/clvk/pull/387 for the Clvk side of things.

**Comment by rjodinchr** [comment]
`CI-clvk-ubuntu-clang-debug` is still failing even after the update of the SPIRV-Headers.
This is because I have added a wrong dependency of the clvk test on `vulkan/vulkan.h`.
[clvk#415](https://github.com/kpet/clvk/pull/415) should fix it.
